### ISSUE TITLE
Access Rights for Developing

### ISSUE THREAD

**Issue by Jubeki** [tiadal/pro-students.de#1]
Hey @tiadal,

Please grant us access rights for this repository so that we can start working on this assignment.

Our usernames are @Jubeki and @FM-2018

Thanks.

Best regards
Julius

**Comment by tiadal** [comment]
Hello @Jubeki,

both of you should have received an invitation. Let me know if it worked.

Mattia

**Comment by Jubeki** [comment]
Yeah it worked.

Thanks.
