### ISSUE TITLE
Site Feedback: General Layout, Course pages, Service Pages and Legal Pages

### ISSUE THREAD

**Issue by FM-2018** [tiadal/pro-students.de#10]
Hello @pre-step  and @tiadal ,

we have finished work on the legal pages (terms, privacy, imprint), course pages (for students, for children, for seniors, for companies) and service pages (for private, for companies). This includes both the desktop and the mobile design. The tablet design may still be a little rough around the edges in some places -- we'll be working on that in due time.

If you like, you can take a look at it at https://tiadal.github.io/pro-students.de/ . You can navigate to the pages using either the navbar, or the links presented in the footer (necessary to reach the legal pages). Please tell us if you find any issues or if you're satisfied with the design.

**Comment by AlbertV11** [comment]
Hello!
I am satisfied with the design.

**Comment by FM-2018** [comment]
Alright, perfect!
