### ISSUE TITLE
Final Inspection

### ISSUE THREAD

**Issue by FM-2018** [tiadal/pro-students.de#12]
Hey @tiadal  and @albertv11 (@pre-step),

we are finished with the implementation of the website. Please take a last look at the finished product at tiadal.github.io/pro-students.de to make sure everything has been implemented as envisioned and works as expected.  Feel free to notify us if there's any further issues. Once you've accepted the final product, we will cease our work and submit it as a final solution on Moodle.

**Comment by tiadal** [comment]
Hello, I am fine with the final result. I just have the following point:
https://tiadal.github.io/pro-students.de/it_support.html please remove 2 videos, since they are duplicated.

Do you agree with it @AlbertV11 or do you have other questions?

Thanks for your work,
Mattia

**Comment by AlbertV11** [comment]
Hello!

I really like the final version of the website.

Thanks,
Albert

**Comment by FM-2018** [comment]
Hey @tiadal and @AlbertV11 ,

the two redundant videos have been removed as wished. With that, the website is officially finished. Thanks for your consistent feedback along the way! Closing this issue now..

Best regards,
Fabian & Julius
