### ISSUE TITLE
Add domain as CNAME

### ISSUE THREAD

**Issue by Jubeki** [tiadal/pro-students.de#13]
Hey @tiadal ,

It would be great if you could add the domain pro-students.kiekbjul.de to this repo. I will then add the corresponding CNAME record to my domain. This would be useful for our SEO assignment.

How to add a domain to this repo can you find here:
https://docs.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

best regards
Julius

**Comment by Jubeki** [comment]
@tiadal are you able to do it?

**Comment by tiadal** [comment]
Website is reachable from http://pro-students.kiekbjul.de/. It is http or https?

**Comment by Jubeki** [comment]
Https ist möglich. Kannst es also auch gerne dauerhaft aktivieren

**Comment by tiadal** [comment]
Alles klar, I activated it :) this should help to achieve a higher score as well

**Comment by Jubeki** [comment]
Thanks.

Seems like I responded in Germand before 😂
