### ISSUE TITLE
Necessary Pages & Contents are missing

### ISSUE THREAD

**Issue by Jubeki** [tiadal/pro-students.de#2]
Hey @tiadal and @pre-step,

Please provide more information about your website.
We would like to start implementing on Tuesday.

Missing information for us:
- Which pages should we implement?
- What content should be on these pages? (some example content would be best)
- Website-Design-Diagram for links on the pages and in the navigation bar on the top.

Thanks.
Fabian and Julius

**Comment by tiadal** [comment]
Hello Fabian and Julios,

![2a_diagram_v7](https://user-images.githubusercontent.com/73166570/102491156-19e6c100-4070-11eb-85e0-42097359aaf1.png)

I attached the diagram with all pages. 

**NAVIGATION BAR:**
LOGO: we didn't come up with a logo yet, you can put a text placeholder within an <a> tag linking to the homepage
MENU ITEMS: 
- computer repairing:
- courses for private persons:
- services for companies:
You can suggest shorter names if you think it's better.
All the other landmark pages can go in the footer.

PAGE CONTENT
I attached a file with the description we wrote for the assignment. The final content is not ready yes, bear in mind it won't be much text, so you can come up with some ideas for the design already and use some placeholder text. 

[Assignment 2a Group 8 Veprev-Dallai (1).pdf](https://github.com/tiadal/pro-students.de/files/5709688/Assignment.2a.Group.8.Veprev-Dallai.1.pdf)

I wish you both a nice week and of course feel free to ask whenever you have a question,
Mattia

**Comment by Jubeki** [comment]
Hey,

we looked through the document and we will start designing soon.  
After we have some basic designs we will ask you to take a look at them and say if you are okay with them before we start implementing them into HTML files.

Right now there is still something missing for this assignment:
- Which site is based on a XML-file?

If you want we can design a logo and provide it as SVG file.

We also would like to know, how the site should feel like:
- Professional
- Playful
- ...

You can also give us the freedom to design the pages how we want and we will look for a design concept.

Best regards. 
Fabian & Julius

**Comment by FM-2018** [comment]
Hello,

one more question has come up regarding the contents, particularly the XML file / course list: how is that XML file going to look like? Is it meant to be one XML file containing all the courses and their data, or is there a separate XML file for each webpage (For students, for seniors, for companies, ...)? What's the XML file structure (i.e. XML schema and / or an example XML file with actual contents)? Or should we define a suitable XML file structure ourselves based on the example courses in your PDF document?

**Comment by FM-2018** [comment]
Closing this one: we've defined the XML format that's needed for creating the pages. Details can be found in the docs/data folder, currently on the dev branch.
