### ISSUE TITLE
Site Feedback: Imprint

### ISSUE THREAD

**Issue by Jubeki** [tiadal/pro-students.de#5]
![imprint html](https://user-images.githubusercontent.com/15707543/103106738-569a5580-4638-11eb-887f-f0343ae9164b.png)

For obvious reasons we choose to add to the legal sites no FAQ Section and remove the call to action buttons which were replaced with links to the other legal pages.

**Comment by tiadal** [comment]
Page style approved.

Please switch the position of the image and the text. 
DESKTOP: image left / text right
MOBILE: image above / text below

**Comment by FM-2018** [comment]
Closing this one; refer to issue #10 for feedback on the concrete implementation
