### ISSUE TITLE
Site Feedback: Terms

### ISSUE THREAD

**Issue by Jubeki** [tiadal/pro-students.de#7]
![terms_and_conditions html](https://user-images.githubusercontent.com/15707543/103106789-ba248300-4638-11eb-8a8a-309232f4ed45.png)

For obvious reasons we choose to add to the legal sites no FAQ Section and remove the call to action buttons which were replaced with links to the other legal pages.

Currently we don't have enough content for the Terms page. Please provide some more text which you want to add there.

**Comment by tiadal** [comment]
Page style approved.

Please switch the position of the image and the text.
DESKTOP: image left / text right
MOBILE: image above / text below

**Comment by FM-2018** [comment]
Closing this one; refer to issue #10 for feedback on the concrete implementation
