### ISSUE TITLE
Site Feedback: About us

### ISSUE THREAD

**Issue by Jubeki** [tiadal/pro-students.de#8]
![about_us html](https://user-images.githubusercontent.com/15707543/103106807-daecd880-4638-11eb-86c9-7d0f1646c24f.png)

We only had 2 Images of the 4 people who are on you team. So we decided to use illustrated avatars as replacement. Is this decision okay with you?

**Comment by tiadal** [comment]
Page style approved.

Please switch the position of the image and the text on the first section
DESKTOP: image left / text right
MOBILE: image above / text below

**Comment by Jubeki** [comment]
Here with an updated first section.

![about_us html-2](https://user-images.githubusercontent.com/15707543/103169797-591acc00-483f-11eb-89b2-4a28d3c8c07f.png)

**Comment by Jubeki** [comment]
Or did you mean the header instead of the avatars?

**Comment by FM-2018** [comment]
Do note that if you meant the header (i.e. the Title "About us" with the illustration on the right), that'd introduce inconsistencies with the other webpages. So far, we were trying to keep header and footer in the same (or if applicable, similar) design on all webpages. Switching around the order of text and image only on this single webpage could therefore be confusing for the users.

**Comment by FM-2018** [comment]
@tiadal 
I see you've given the same feedback on most of the other issues, too, so you probably _are_ referring to the header. If you want us to do that switch on all pages (including e.g. the IT courses), then it's no problem, of course.

**Comment by tiadal** [comment]
I mean the section above the fold,in this case:
1)the image with the 4 people 
2)about us, text and the 2 buttons.

please invert them so that the picture is on the left side and on mobile the first thing to appear 

thanks and sorry that I wasn't clear enough :) 
Mattia

**Comment by FM-2018** [comment]
Closing this one; a new issue will be created once we can provide you with real implementation results
