### ISSUE TITLE
Site Feedback: IT Courses for companies / private / children / students / seniors

### ISSUE THREAD

**Issue by Jubeki** [tiadal/pro-students.de#9]
![it_courses_for_companies html-2](https://user-images.githubusercontent.com/15707543/103106902-bcd3a800-4639-11eb-8637-daa3dfde3a23.png)

For completeness of all pages you can provide also feedback here.

We would design all IT-Course pages like this and just change their content accordingly. Do you have any problems with that?

**Comment by Jubeki** [comment]
![it_courses_for_companies html tablet](https://user-images.githubusercontent.com/15707543/103134198-dfa0a380-46af-11eb-9074-0bcbfc26f606.png)
![it_courses_for_companies html mobile](https://user-images.githubusercontent.com/15707543/103134199-e3342a80-46af-11eb-9ba0-5dbb92b44947.png)

@tiadal @pre-step we added a mobile and tablet view for you for this example. So you can take a look at the navbar and footer.

**Comment by tiadal** [comment]
The design looks great, you can proceed with the real coding.
